

#*******************************#*******************************
#*******************************#*******************************
#*******************************#*******************************
#Alternatively, you can create a constructor

class DocumentModifier:
  def __init__(self, filename):
    self.filename = filename

  def change_content(self, old_text, new_text):
    # Open the file in read mode
    with open(self.filename, 'r') as file:
      # Read the contents of the file
      content = file.read()

    # Modify the content of the file
    content = content.replace(old_text, new_text)

    # Open the file in write mode
    with open(self.filename, 'w') as file:
      # Write the modified content to the file
      file.write(content)

# To use the DocumentModifier class, you would create an instance of the class and call the change_content method:
modifier = DocumentModifier('Carsec_AutoGenerated.txt')
old_text ='CARSECN'
new_text ='Hello_CFC'
modifier.change_content(old_text,new_text)


#*******************************#*******************************
#*******************************#*******************************
#*******************************#*******************************
