

#*******************************#*******************************
# Create a constructor

class DocumentModifier:
  def __init__(self, filename):
    self.filename = filename

  def change_content(self, my_dict={}):
    # Open the file in read mode
    with open(self.filename, 'r') as file:
      # Read the contents of the file
      content = file.read()

    # Modify the content of the file
    #content = content.replace(old_text, new_text)# this is only for one word

    for old_text in my_dict.keys():
      # Replace the old text with the new text if it is present in the "text" variable
      content = content.replace(old_text, my_dict[old_text])

    # Open the file in write mode
    with open(self.filename, 'w') as file:
      # Write the modified content to the file
      file.write(content)

#*******************************#*******************************
# To use the DocumentModifier class, you would create an instance of the class and call the change_content method:

Dict={"Tipo":"Type", "Unidades": "Units"}
modifier = DocumentModifier('Carsec_AutoGenerated.txt')
old_text ='CARSECN'
new_text ='Hello_CFC'
modifier.change_content(Dict)
#*******************************#*******************************
#*******************************#*******************************
#*******************************#*******************************

